stud={"name":"Rihala","age":21,"sem":1,"roll no":31}
print(stud)
print(len(stud))
print(stud.keys())
print(stud.values())
print(stud.items())
stud.update({"gender":"male"})
print(stud)
stud.pop("sem")
print(stud)