print("hello,world")

name=input("enter name")
print(name)
age=input("enter age:")
print(age)
username=input("enter username")
print("username is:"+username)
password=input("enter password:")
print("password is:"+password)
phone=(input("enter phone number"))
print("no. is:"+phone)
