stud={"name":"aswani","age":25,"sem":1,"roll no":13}
print(stud)
print(len(stud))
print(stud.keys())
print(stud.values())
print(stud.items())
stud.update({"gender":"female"})
print(stud)
stud.pop("sem")
print(stud)
